# production aws_ec2.yml
plugin: aws_ec2
boto_profile: slalom-innovation
cache: yes
cache_plugin: jsonfile
cache_timeout: 20
cache_connection: /tmp/aws_inventory
cache_prefix: aws_ec2
regions:
  - us-west-2

filters:
  tag:Email: "gus.price@slalom.com"

keyed_groups:

  #list all hosts by their tag groups.
  - key: tags
    prefix: "tag"
    separator: "_"

  #list all hosts by their instance id.
  - key: instance_id
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address
